services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    plan: free
    runtime: python
    region: frankfurt
    branch: main
    autoDeploy: true
